# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: lzk199504272024@163.com
    password: UCKXKKHQCLHUTDNE
    port: 465
    properties:
      from: lzk199504272024@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: localhost
    username: kevin
    password: 123456
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: kevin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: http://localhost:9000
    username: adminminio
    password: adminminio
